name: create-quarto

on:
  push:
    branches:
      - create_quarto

jobs:
    create_quarto:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oleksiyrudenko/gha-git-credentials@v2-latest
              with:
                token: '${{ secrets.GITHUB_TOKEN }}'
            - run: |
                wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.551/quarto-1.4.551-linux-amd64.tar.gz
                mkdir ~/opt
                tar -C ~/opt -xvzf quarto-1.4.551-linux-amd64.tar.gz
                mkdir ~/bin
                ln -s ~/opt/quarto-1.4.551/bin/quarto ~/bin/quarto
                ( echo ""; echo 'export PATH=$PATH:~/bin\n' ; echo "" ) >> ~/.profile
                source ~/.profile
                quarto check
                cd .github/workflows
                pip install nbformat nbclient
                pip install jupyter matplotlib plotly
                quarto render quarto_test.qmd
                cp quarto_test_files/figure-html/fig-polar-output-1.png ../../src/assets/
                git add ../../src/assets/fig-polar-output-1.png
                git commit -m 'Update graph for blog'
                git push origin HEAD