name: download-data

on:
    schedule:
        # Run everyday at 2:00pm CST which is 7:00pm UTC
        - cron: 0 19 * * *

    # Allows the workflow to be run manually from the Actions tab
    workflow_dispatch:

jobs:
    download-data-json:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: download data
              uses: ./.github/actions/download-from-s3
              with:
                file-path: data.json
            - name: download schedule vs realtime
              uses: ./.github/actions/download-from-s3
              with:
                file-path: schedule_vs_realtime_all_day_types_routes.json