name: download-ridership-data

on:
    schedule:
        # Run monthly at 2:00pm CST which is 7:00pm UTC
        - cron: 30 19 1 * *
    
    # Allows the workflow to be run manually from the Actions tab
    workflow_dispatch:

jobs:
    download-data-json:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: download ridership data
              uses: ./.github/actions/download-from-s3
              with:
                file-path: cta_ridership_data_day_type_summary.json

            - uses: oleksiyrudenko/gha-git-credentials@v2-latest
              with:
                token: '${{ secrets.GITHUB_TOKEN }}'
            - run: |
                git add .
                git commit -m 'Add updated ridership data that was downloaded from s3'
                git push origin main