name: download-data
on:
  push:
    branches:
      - test_commit_routes

jobs:
    download-data-json:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - run: |
                 wget https://chn-ghost-buses-public.s3.us-east-2.amazonaws.com/frontend_data_files/data.json \
                    -O src/Routes/data.json
                 wget \
                    https://chn-ghost-buses-public.s3.us-east-2.amazonaws.com/frontend_data_files/schedule_vs_realtime_all_day_types_routes.json \
                    -O src/Routes/schedule_vs_realtime_all_day_types_routes.json

            - uses: oleksiyrudenko/gha-git-credentials@v2-latest
              with:
                token: '${{ secrets.GITHUB_TOKEN }}'
            - run: |
                git add .
                git commit -m 'Add downloaded file'