name: download-data

on:
  push:
    branches:
      - reusable-s3-download-action

jobs:
    download-data-json:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: download data
              uses: ./.github/actions/download-from-s3
              with:
                file-path: data.json
            - name: download schedule vs realtime
              uses: ./.github/actions/download-from-s3
              with:
                file-path: schedule_vs_realtime_all_day_types_routes.json